### ISSUE TITLE
Link no README e problemas no HTTPS

### ISSUE THREAD

**Issue by ppKrauss** [Plataformas-Cidadania/mapaosc#21]
Apenas lembrete, se este for o local mais adequado  para comentar:

* o [README](https://github.com/Plataformas-Cidadania/mapaosc/blob/master/README.md) poderia acrescentar o link ao citar "mapaosc.ipea.gov.br", ou seja, usar  `[mapaosc.ipea.gov.br](http://mapaosc.ipea.gov.br)`.
  
* atualmente o site http://mapaosc.ipea.gov.br/  é redirecionado ao respectivo HTTPS que por sua vez está gerando uma mensagem do tipo "Há um problema no certificado de segurança do site" no navegador.  O ideal seria o uso de HTTP, visto que são dados públicos e que os usuários não estão preocupados com  sigilo durante a navegação.

**Comment by raulsenaferreira** [comment]
O primeiro item foi corrigido para os links não só do mapa mas também das dependências.
O segundo item é causado por problema entre o certificado brasileiro e o Mozilla. O problema não ocorre nem no Chrome nem o Edge/IE.
Sendo assim, o primeiro item resolvido e o segundo sendo um problema que foge ao nosso escopo, darei esta issue como fechada.
@ppKrauss Obrigado pela dica e sinta-se a vontade para abrir outras issues quando necessário.
P.S.: Uma nova versão do mapa está sendo desenvolvida com novas tecnologias, sendo assim, o repositório está pra ser atualizado, este projeto será quase todo reescrito.
