### ISSUE TITLE
Opção de interface textual

### ISSUE THREAD

**Issue by ppKrauss** [Plataformas-Cidadania/mapaosc#22]
Por ser uma base de dados confiável, rica e relevante, os usuários procuram o "Mapa das OSCs" não apenas para localização espacial...

Sente-se falta da busca por CNPJ e de uma opção de busca textual (mesmo que link para outra página), ou seja, mostrando apenas a "ficha catalográfica da organização", sem a obrigação de se navegar pelo mapa ou clicar nos pontos.

**Comment by EricFerreiraS** [comment]
Essa ideia foi implementada na versão 2.0 do mapa, na página principal.
