### ISSUE TITLE
Indicar versões PostgreSQL e PostGIS

### ISSUE THREAD

**Issue by ppKrauss** [Plataformas-Cidadania/mapaosc#23]
No README não são indicadas as versões. 
## Tentativa de instalação da base de dados em Pg9.5 e PostGIS 2.2

Num terminal de UBUNTU 14 LTS,

``` bash
wget -c http://repositorio.dados.gov.br/pessoa-familia-sociedade/sociedade-civil-organizacao-participacao/mapa-oscs.7z
7z x -so mapa-oscs.7z 2> /dev/null | psql -h localhost -U postgres mapaosc
```

Não teve sucesso, diversas mensagens do tipo _"ERRO: não pôde acessar arquivo $libdir/rtpostgis-2.1: Arquivo ou diretório não encontrado"_.  

Ideal seria disponibilizar opções de _download_ da base  (há outro além do repositorio.dados.gov.br?)  compatíveis com as versões mais atuais.

**Comment by EricFerreiraS** [comment]
Sobre as versões, ver em https://github.com/Plataformas-Cidadania/portalosc/wiki/2.-Instala%C3%A7%C3%A3o
Sobre a base de dados, não estão mais disponíveis os dados em forma agregada pois continha dados sensíveis. Os dados que podem ser obtidos estão no link https://mapaosc.ipea.gov.br/base-dados.html
A base presente no dados.gov.br é de uma versão antiga e descontinuada.
