### ISSUE TITLE
Dump do PostGreSQL ou Resultado CSV da pesquisa com dados geográficos incluídos.

### ISSUE THREAD

**Issue by marcoarthur** [Plataformas-Cidadania/mapaosc#25]
Antes havia um dump que estava no portal dados.gov.br dessa base, eu estava interessado em ter esse dump já que o site não disponibiliza o conteúdo csv da pesquisa com os dados de latitude/longitude dos pontos mapeados o que é uma lástima, diga-se de passagem. Meu projeto era colocar esses pontos no OpenStreetMap.

**Comment by EricFerreiraS** [comment]
Olá,
Infelizmente as informações como endereço, telefone e e-mail foram retiradas de consultas agregadas para que esses dados não fossem utilizados de maneira que expusesse informações sensíveis. Os dados que podem ser baixados da plataforma se encontram em https://mapaosc.ipea.gov.br/base-dados.html

**Comment by marcoarthur** [comment]
Olá,

Não faz muito sentido a resposta, já que uma organização da sociedade civil tem fins de atender a sociedade.
